// Curated global amusement / gaming / anime trade shows (manually maintained).
export const SHOWS = [
  { name: 'GTI Asia Pacific Expo 2026', city: 'Guangzhou', venue: 'Poly World Trade Center', country: 'China', startDate: '2026-03-28', endDate: '2026-03-30', category: 'Amusement', region: 'asia', flag: '🇨🇳', scale: '800+ Exhibitors', description: "Asia's largest amusement and gaming equipment trade show, covering arcade, VR, redemption and FEC solutions.", url: 'https://www.gtishow.com/', featured: 1 },
  { name: 'AAE Asia Amusements & Attractions Expo 2026', city: 'Singapore', venue: 'Singapore Expo', country: 'Singapore', startDate: '2026-04-15', endDate: '2026-04-17', category: 'Amusement', region: 'asia', flag: '🇸🇬', scale: '350+ Exhibitors', description: "Southeast Asia's premier amusement industry platform connecting suppliers and operators across 14 ASEAN markets.", url: '', featured: 0 },
  { name: 'AAMA Annual Conference & Expo 2026', city: 'Las Vegas', venue: 'Bellagio Hotel', country: 'USA', startDate: '2026-06-05', endDate: '2026-06-08', category: 'Conference', region: 'americas', flag: '🇺🇸', scale: '200+ Attendees', description: "Amusement and Music Operators Association flagship event for North American FEC and route operators.", url: '', featured: 0 },
  { name: 'DEAL Expo 2026', city: 'Dubai', venue: 'Dubai World Trade Centre', country: 'UAE', startDate: '2026-07-22', endDate: '2026-07-25', category: 'Amusement', region: 'middleeast', flag: '🇦🇪', scale: '300+ Exhibitors', description: "Middle East and North Africa's leading event for the amusement, leisure and entertainment industry.", url: '', featured: 0 },
  { name: 'EAG International Expo 2026', city: 'London', venue: 'ExCeL London', country: 'UK', startDate: '2026-09-14', endDate: '2026-09-17', category: 'Amusement', region: 'europe', flag: '🇬🇧', scale: '400+ Exhibitors', description: "Europe's leading trade show for the amusement, gaming machines and entertainment industry.", url: '', featured: 1 },
  { name: 'IAAPA Expo Europe 2026', city: 'Barcelona', venue: 'Fira de Barcelona', country: 'Spain', startDate: '2026-10-08', endDate: '2026-10-10', category: 'Attractions', region: 'europe', flag: '🇪🇸', scale: '500+ Exhibitors', description: "IAAPA's European flagship event covering theme parks, water parks, FECs and attractions.", url: '', featured: 0 },
  { name: 'IAAPA Expo 2026', city: 'Orlando', venue: 'Orange County Convention Center', country: 'USA', startDate: '2026-11-18', endDate: '2026-11-21', category: 'Attractions', region: 'americas', flag: '🇺🇸', scale: '1,200+ Exhibitors', description: "The world's largest trade show for the attractions industry.", url: 'https://www.iaapa.org/expo', featured: 1 },
  { name: 'Anime Expo 2026', city: 'Los Angeles', venue: 'Los Angeles Convention Center', country: 'USA', startDate: '2026-07-02', endDate: '2026-07-05', category: 'Anime', region: 'americas', flag: '🇺🇸', scale: '100K+ Visitors', description: "North America's largest anime convention and industry gathering.", url: 'https://www.anime-expo.org/', featured: 0 },
  { name: 'Comiket 108', city: 'Tokyo', venue: 'Tokyo Big Sight', country: 'Japan', startDate: '2026-08-15', endDate: '2026-08-16', category: 'Anime', region: 'asia', flag: '🇯🇵', scale: '500K+ Visitors', description: "The world's largest doujinshi (self-published) anime/manga convention.", url: '', featured: 0 },
  { name: 'China Amusement Expo (CAE) 2026', city: 'Beijing', venue: 'China International Exhibition Center', country: 'China', startDate: '2026-05-20', endDate: '2026-05-22', category: 'Amusement', region: 'asia', flag: '🇨🇳', scale: '600+ Exhibitors', description: "China's national amusement equipment expo covering rides, playground and FEC equipment.", url: '', featured: 0 },
  { name: 'Euro Attractions Show (EAS) 2026', city: 'Barcelona', venue: 'Fira de Barcelona', country: 'Spain', startDate: '2026-10-08', endDate: '2026-10-10', category: 'Attractions', region: 'europe', flag: '🇪🇸', scale: '400+ Exhibitors', description: "Major European attractions industry tradeshow by IAAPA.", url: '', featured: 0 },
  { name: 'Gamescom 2026', city: 'Cologne', venue: 'Koelnmesse', country: 'Germany', startDate: '2026-08-26', endDate: '2026-08-30', category: 'Gaming', region: 'europe', flag: '🇩🇪', scale: '370K+ Visitors', description: "The world's largest gaming event, with strong B2B industry zone.", url: 'https://www.gamescom.global/', featured: 1 },
  { name: 'Dubai Entertainment Amusement Expo 2026', city: 'Dubai', venue: 'Dubai World Trade Centre', country: 'UAE', startDate: '2026-11-03', endDate: '2026-11-05', category: 'Amusement', region: 'middleeast', flag: '🇦🇪', scale: '250+ Exhibitors', description: "Dedicated entertainment and amusement expo for the Gulf region.", url: '', featured: 0 },
  { name: 'Tokyo Game Show 2026', city: 'Chiba', venue: 'Makuhari Messe', country: 'Japan', startDate: '2026-09-24', endDate: '2026-09-27', category: 'Gaming', region: 'asia', flag: '🇯🇵', scale: '200K+ Visitors', description: "Japan's premier game industry trade and consumer show.", url: 'https://tgs.cesa.or.jp/', featured: 0 },
  { name: 'IAAPA Expo Asia 2027', city: 'Shanghai', venue: 'Shanghai New International Expo Centre', country: 'China', startDate: '2027-04-14', endDate: '2027-04-16', category: 'Attractions', region: 'asia', flag: '🇨🇳', scale: '500+ Exhibitors', description: "IAAPA's Asia-Pacific attractions expo.", url: '', featured: 0 },
  { name: 'GTI Asia Pacific Expo 2027', city: 'Guangzhou', venue: 'Poly World Trade Center', country: 'China', startDate: '2027-03-30', endDate: '2027-04-01', category: 'Amusement', region: 'asia', flag: '🇨🇳', scale: '800+ Exhibitors', description: "Next edition of Asia's largest amusement equipment trade show.", url: 'https://www.gtishow.com/', featured: 0 }
];

// Targeted exhibitions requested by the operator.
// Dates are hard-coded based on the operator's verified schedule and updated by year.
export const TARGETED_SHOWS = [
  { name: 'Korea Theme Park & Amusement Fair (KAAF)', city: 'Goyang', venue: 'KINTEX', country: 'South Korea', startDate: '2026-07-20', endDate: '2026-07-22', category: 'Amusement', region: 'asia', flag: '🇰🇷', scale: '', description: "Korea's leading theme park and amusement industry trade fair.", url: 'https://www.kaafair.com', featured: 0 },
  { name: 'TTG SIA SUN — Italian Tourism Expo', city: 'Rimini', venue: 'Rimini Expo Centre', country: 'Italy', startDate: '2026-10-14', endDate: '2026-10-16', category: 'Trade Show', region: 'europe', flag: '🇮🇹', scale: '', description: "Italy's international tourism, travel and attractions industry trade show.", url: 'https://www.ttgexpo.it', featured: 0 },
  { name: 'Sports Betting East Africa (SBEA)', city: 'Nairobi', venue: '', country: 'Kenya', startDate: '2026-10-20', endDate: '2026-10-21', category: 'Betting', region: 'africa', flag: '🇰🇪', scale: '', description: "East Africa's sports betting and gaming industry conference.", url: 'https://www.sportsbettingevents.com/sbea', featured: 0 },
  { name: 'Betting on Sports Europe', city: 'London', venue: '', country: 'UK', startDate: '2026-10-20', endDate: '2026-10-22', category: 'Betting', region: 'europe', flag: '🇬🇧', scale: '', description: "Europe's leading sports betting and gaming conference.", url: 'https://www.sbcevents.com/betting-on-sports-europe', featured: 0 },
  { name: 'NRPA Annual Conference & Expo', city: '', venue: '', country: 'USA', startDate: '2026-10-27', endDate: '2026-10-29', category: 'Conference', region: 'americas', flag: '🇺🇸', scale: '', description: "National Recreation and Park Association annual conference for parks, recreation and leisure industry.", url: 'https://www.nrpa.org/conference/', featured: 0 },
  { name: 'Thailand Amusement & Attraction Parks Expo (TAAPE)', city: 'Bangkok', venue: '', country: 'Thailand', startDate: '2026-10-28', endDate: '2026-10-30', category: 'Amusement', region: 'asia', flag: '🇹🇭', scale: '', description: "Thailand's amusement, attraction and parks industry expo.", url: 'https://www.taape.cn', featured: 0 },
  { name: 'Theme Park Vietnam Technology Meet', city: '', venue: '', country: 'Vietnam', startDate: '2026-11-03', endDate: '2026-11-06', category: 'Theme Park', region: 'asia', flag: '🇻🇳', scale: '', description: "Vietnam's theme park technology and attractions conference.", url: 'https://www.themeparkvietnam.com', featured: 0 },
  { name: 'Cyprus Gaming Show (CGS)', city: '', venue: '', country: 'Cyprus', startDate: '2026-11-09', endDate: '2026-11-10', category: 'Gaming', region: 'europe', flag: '🇨🇾', scale: '', description: "Cyprus international gaming and betting expo.", url: 'https://www.cyprusgamingshow.com', featured: 0 },
  { name: 'SiGMA Malta', city: '', venue: '', country: 'Malta', startDate: '2026-11-17', endDate: '2026-11-19', category: 'Gaming', region: 'europe', flag: '🇲🇹', scale: '', description: "One of the world's largest iGaming and betting expos.", url: 'https://sigma.com.mt', featured: 0 },
  { name: 'GTI ASIA CHINA EXPO', city: 'Guangzhou', venue: '', country: 'China', startDate: '2026-03-28', endDate: '2026-03-30', category: 'Amusement', region: 'asia', flag: '🇨🇳', scale: '', description: "GTI's China amusement and gaming equipment expo.", url: 'https://gtichinaamuse.com/home/gtiindex?id=4895', featured: 0 }
];
